### PR TITLE
Remove deprecated WebformElements.php

### PR DESCRIPTION
**Pull request by askibinski**
This is the old WebformElements field which should be deleted. It was dependent on JsonObject but conflicts with the new `GraphQL\Fields\Element\WebformElements`.

### CODE REVIEW

**Comment by carolpettirossi** [comment]
Hi askibinski, 

Thanks for reporting this issue. The code was actually outdated and I'm sorry about that. I've just pushed a new version to the dev branch.
The `WebformElements` is actually necessary to:

1. Add the `plugin` and allow future checks in each WebformElement type.

For example, `WebformElementCheckboxes` has this check 

```
  public function applies($object, ResolveContext $context, ResolveInfo $info) {
    return $object['plugin'] instanceof Checkboxes;
  }
```

2. Add elements of the `Webform` and `WebformComposite` to allow this kind of query for example.

```
{
  webformById(webform_id: "contact") {
    __typename
    description
    elements {
      __typename
      id
      type
      ... on WebformElementTextarea {
        title
      }
      ... on WebformElementComposite {
        elements {
          id
          type
          ... on WebformElementTextField {
            title
          }
        }
      }
    }
  }
}
```
Would you mind testing the latest version pushed to dev branch?

Thanks,
Carol

**Comment by askibinski** [comment]
Thanks for the update, I've tested it using graphql 3.x and this latest dev I get the following error (from Drupal logs):

> Missing type JsonObject.

So I'm confused how this should works since the [plugin](https://github.com/duartegarin/graphql_webform/blob/dev/src/Plugin/GraphQL/Fields/WebformElements.php) occupies the same plugin_id ("webform_elements") as this [plugin](https://github.com/duartegarin/graphql_webform/blob/dev/src/Plugin/GraphQL/Fields/Element/WebformElements.php). And also it uses JsonObject type while this dependency was removed in this [commit](https://github.com/duartegarin/graphql_webform/commit/5a6f6d9020db9151f05bbbe1a6dc4b3e27e5a0dd).

**Comment by carolpettirossi** [comment]
askibinski, sorry about that. Forgot to delete some files. I just pushed the updates. The module should work now.

**Comment by carolpettirossi** [comment]
Closing this PR since it's related to an outdated version.

**Pull request closed without merging**
